zepben/ewb-super-pom

pom.xml

Process annotations prior to compilation

---

pom.xml

Update kotlin to 1.4.30, add serialisation lib and remove kapt

---

pom.xml

Update kotlin to 1.5.21 and add extra kotlin dependencies

---

pom.xml

Update to latest version of grpc

---

pom.xml

Update mockito versions

---

pom.xml

Add azure BOM dependency

---

pom.xml

Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

Update commons-csv dependency to 1.9.0

---

pom.xml

Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

Add dom4j dependency

---

pom.xml

Add hikaryCP dependency and promote version
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>

Add dependency on hikaryCP for DB connection pooling

---

pom.xml

Update protobuf and grpc versions

---

pom.xml

Update to the super-pom where all the KTOR dependencies and ktor version are specified. These are required by the powerfactory-model-service
None of the item in the list were relevant because this was an update to the super-pom

- Added KTOR dependencies

---

pom.xml

- Updated graphql dependencies to latest versions
- Added graphql-java dependency
- Updated graphql-java-extended-scalars version
Signed-off-by: Roberto Marquez Vasquez <roberto.marquez@zepben.com>
- Updated graphql dependencies to latest versions
- Added graphql-java dependency
- Updated graphql-java-extended-scalars version
EWB-1884
EWB-1885
EWB-1886
EWB-1887
EWB-1888
These are always required, if you do not do them, reviewers will be angry:
re: The super-pom has no tests.

Updated graphql dependencies

---

README.md
pom.xml

Add [caffeine](https://github.com/ben-manes/caffeine) to dependencyManagement. This a reputed and well tested in memory caching library.
None.
These are always required, if you do not do them, reviewers will be angry:

Add caffeine (cache library) to dependencyManagement.

---

pom.xml

Added Apache Lucene to dependency management.

Add apache lucene to dependencyManagement.

---

pom.xml

See title. We are doing this as a part of a larger task to build a CLI tool for HC/EWB.
Tasks blocking this one:
- None
Tasks this is blocking:
- None
These are always required, if you do not do them, reviewers will be angry:
These you can remove from the list if they are not applicable for this PR.

Update Clikt dependency from 3.2.0 to 4.2.0

---

changelog.md
pom.xml

Update dependencies with registered vulnerabilities (CVE) to the latest non-beta version.
Tasks blocking this one:
- None
Tasks this is blocking:
- None
Two packages have group ID changes due to being moved in maven central: unirest-java (com.mashape.unirest ➝ com.konghq), dom4j (dom4j ➝ com.dom4j).

EWB-4086: Update vulnerable dependencies

---

changelog.md
pom.xml

Add lucene-analysis-common and update lucene version to 9.9.2
None.
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have updated any documentation required for these changes.~
No breaking changes known.

Add lucene-analysis-common and update lucene version to 9.9.2

---

for-ci-build-image/maven-settings.xml

Fixing gpg configuration to properly use the provided parameters.
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~

Fix gpg configuration

---

changelog.md
pom.xml

Full description available here https://github.com/zepben/evolve-app-server/pull/73. This PR upstreams the testcontainers dependency in linked PR inline with how we do third party dependencies
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
- https://github.com/zepben/evolve-app-server/pull/73 - this PR goes after this pr

[DEV-122] Add TestContainers Dependency

---

pom.xml

Update dokka version

---

changelog.md
pom.xml

Added new library Aws SDK S3.
This repo has been hijacked and an attempt has been made to manually update the pom version and changelog.
Shouldn't have any dependency.
Testing can be done by inheriting pom and specifying dependency.
No tests
No related docs.
Not a breaking change.

Add aws sdk dependency

---

.github/workflows/build-container.yml
for-ci-build-image/build-container.pkr.hcl
pom.xml

An update to the `pipeline-java-ewb` container build flow to allow remote execution and payload parsing.
- https://github.com/zepben/ci-utils/pull/19
- https://github.com/zepben/.github/pull/52
~- [] I have updated the changelog.~
~- [] I have updated any documentation required for these changes.~

[OPS-256] Remote container build

---

for-ci-build-image/maven-settings.xml

This change ads a custom header to maven requests to Zepben's Nexus.
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
~- [ ] I have updated the changelog.~
~- [ ] I have updated any documentation required for these changes.~
Not a breaking change.

[OPS-285] Add custom header field to maven requests

---

changelog.md
pom.xml

Updates versions
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
Removes the protobuf compilation plugin - this is breaking but is now handled in ewb-grpc directly

[DEV-2894] Update protobuf and gRPC to latest versions

---

.github/workflows/build-container.yml
.github/workflows/check-and-tag.yml
.github/workflows/check-version.yml
.github/workflows/release.yml

Workflow fixes and updates
- Fix fetching version from the current latest image
- Restore payload when launching container build
- Bump checkout and repository-dispatch versions

Workflow fixes and updates

---

.github/workflows/build-container.yml
.github/workflows/release.yml
changelog.md
pom.xml

Fix Maven Central username and password

Fix ossrh params

---

.github/workflows/release.yml
changelog.md
pom.xml

Using proper maven-central profile

Using proper maven-central profile

---

changelog.md
pom.xml

Enable auto-publish
